### PR TITLE
fix @Inject decorator for Http

### PR DESCRIPTION
**Pull request by phra**
hi,

please accept this PR to fix resolution of Http provider. (i'm testing your fork w/ this project -> https://github.com/phra/loopback-angular2-boilerplate)

### CODE REVIEW

**Comment by mnvx** [comment]
Thank you for contribution! Could you explain why necessary to declare `http` parameter with `@Inject`? It works for me just with `@Injectable` declaration

**Comment by phra** [comment]
hi,

i've to do so because if you compile the .ts file alone to .js and include it in another project, like this one (https://github.com/phra/angular2-es6-todomvc) that uses ES6 (babel) without typescript, the parameter metadata of services are lost, ie. angular2 DI does not know the type of the Http parameter.
if you decorate the Http parameter with the @Inject decorator typescript will output the missing metadata and angular2 will work.

EDIT: i've found the solution reading this -> http://blog.thoughtram.io/angular/2015/09/17/resolve-service-dependencies-in-angular-2.html after getting "Cannot resolve all parameters for BaseLoopBackApi(?). Make sure they all have valid type or annotations."

**Comment by phra** [comment]
in addition, i've taken this screenshot:

the line:
__param(0, core_1.Inject(http_1.Http))
is missing if you compile it alone.

screenshot from 2016-02-29 14 47 48

**Comment by phra** [comment]
is it normal that there are 4 definition of UserApi.prototype.user? (i don't think so)
it seems to me a bug w/ the relations of User model.
could you help me to fix this one?
thanks.

screenshot from 2016-02-29 14 54 08

**Comment by mnvx** [comment]
Ok, thanks, I will explore this situation today. I build js files with approach described in [angular tutorial](https://angular.io/docs/ts/latest/quickstart.html).

**Comment by phra** [comment]
this is a comparison of generated code for angular1 and angular2.
in angular2 UserApi.prototype.user is defined 4 times (they are all relations) instead in angular1 they all have different names.
thanks for your help.

screenshot from 2016-02-29 15 49 17

**Comment by mnvx** [comment]
Thank you for feedback. I not found good reasons for these methods and removed them [here](https://github.com/Qeti/loopback-sdk-angular/commit/2af717820aae7b69e3e2dd83c58182c1ded2d2c5)

**Comment by sylvaindumont** [comment]
```
if (action.internal) {
   return;
}
```

remove all related model functions, example :

```
  // INTERNAL. Use Category.products.findById() instead.
  public ::findById::category::products(id: any, fk: any)
```

See #2 for fix

**Pull request merged**
